// <auto-generated />
using System;
using FinLog.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinLog.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126092731_AddAccountBasedFields")]
    partial class AddAccountBasedFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinLog.Server.Models.Account", b =>
                {
                    b.Property<int>("account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("account_id"));

                    b.Property<string>("account_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("account_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("uid")
                        .HasColumnType("integer");

                    b.HasKey("account_id");

                    b.HasIndex("uid");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("FinLog.Server.Models.Category", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cid"));

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("uid")
                        .HasColumnType("integer");

                    b.HasKey("cid");

                    b.HasIndex("uid");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("FinLog.Server.Models.Expense", b =>
                {
                    b.Property<int>("eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("eid"));

                    b.Property<int>("account_id")
                        .HasColumnType("integer");

                    b.Property<int>("cid")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<decimal>("eamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("edate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("uid")
                        .HasColumnType("integer");

                    b.HasKey("eid");

                    b.HasIndex("account_id");

                    b.HasIndex("cid");

                    b.HasIndex("uid");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("FinLog.Server.Models.Income", b =>
                {
                    b.Property<int>("iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("iid"));

                    b.Property<int>("account_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("uid")
                        .HasColumnType("integer");

                    b.HasKey("iid");

                    b.HasIndex("account_id");

                    b.HasIndex("uid");

                    b.ToTable("Income");
                });

            modelBuilder.Entity("FinLog.Server.Models.Transactions", b =>
                {
                    b.Property<int>("tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tid"));

                    b.Property<int>("account_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("ref_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("tamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ttype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("uid")
                        .HasColumnType("integer");

                    b.HasKey("tid");

                    b.HasIndex("account_id");

                    b.HasIndex("uid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinLog.Server.Models.User", b =>
                {
                    b.Property<int>("uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uid"));

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("uid");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("FinLog.Server.Models.Account", b =>
                {
                    b.HasOne("FinLog.Server.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinLog.Server.Models.Category", b =>
                {
                    b.HasOne("FinLog.Server.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinLog.Server.Models.Expense", b =>
                {
                    b.HasOne("FinLog.Server.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinLog.Server.Models.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("cid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinLog.Server.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinLog.Server.Models.Income", b =>
                {
                    b.HasOne("FinLog.Server.Models.Account", "Account")
                        .WithMany("Incomes")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinLog.Server.Models.User", "User")
                        .WithMany("Incomes")
                        .HasForeignKey("uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinLog.Server.Models.Transactions", b =>
                {
                    b.HasOne("FinLog.Server.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinLog.Server.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinLog.Server.Models.Account", b =>
                {
                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("FinLog.Server.Models.Category", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("FinLog.Server.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Categories");

                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
