// <auto-generated />
using FinLog.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinLog.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251011084154_createcategory")]
    partial class createcategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinLog.Server.Models.Category", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cid"));

                    b.Property<int?>("Useruid")
                        .HasColumnType("integer");

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("uid")
                        .HasColumnType("integer");

                    b.HasKey("cid");

                    b.HasIndex("Useruid");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("FinLog.Server.Models.User", b =>
                {
                    b.Property<int>("uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uid"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("uid");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FinLog.Server.Models.Category", b =>
                {
                    b.HasOne("FinLog.Server.Models.User", null)
                        .WithMany("Categories")
                        .HasForeignKey("Useruid");
                });

            modelBuilder.Entity("FinLog.Server.Models.User", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
